# Generated by Django 5.2.8 on 2025-11-28 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="scanner.document"
            ),
        ),
    ]
